In [1]:
import numpy as np

In [41]:
letter_array = np.array(['a','b','c','d','e','f','g','h','i','j'])
print(letter_array.dtype)
print(letter_array.shape)
print(letter_array.size)

<U1
(10,)
10


In [52]:
print(np.full((3,4),'5', dtype=int))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [70]:
X = np.arange(20).reshape(4,5)
print(X)
z = np.copy(X[:,2:3])
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 2]
 [ 7]
 [12]
 [17]]


In [77]:
import pandas as pd
ser=pd.Series(data=[1,2,3,4], index = ['One','Two','Three','Four'])
ser.index
ser.values

array([1, 2, 3, 4])

In [79]:
?pd.DataFrame